version: 1.0.5
name: discordio
summary: A multipurpose discord bot
description: dio #https://github.com/dada513/Discordio
grade: devel
base: core18
confinement: devmode

parts:
  node:
    plugin: nodejs
    nodejs-version: "12.19.0"
    nodejs-package-manager: "yarn"
    source: .

apps:
  discordio:
    command: /usr/bin/node launcher.js
    daemon: simple
    restart-delay: 5s
