name: discordio
version: git
summary: A multipurpose discord bot
description: https://github.com/dada513/Discordio

base: core18
confinement: devmode

parts:
  discordio:
    plugin: nodejs
    source: https://github.com/dada513/Discordio/archive/master.tar.gz

apps:
  discordio:
    command: discordio
    daemon: simple
