summary: A multipurpose discord bot
description: https://github.com/dada513/Discordio

base: core18
confinement: devmode

parts:
  discordio:
    plugin: nodejs
    nodejs-version: "12.19.0"
    nodejs-package-manager: "yarn"
    source-type: git
    source: https://github.com/dada513/Discordio.git

apps:
  discordio:
    command: discordio
    daemon: simple
    restart-delay: 5s
