export default [
  {
    id: "2",
    typeName: "QUAKECRAFT",
    databaseName: "Quake",
    cleanName: "Quake",
  },
  {
    id: "3",
    typeName: "WALLS",
    databaseName: "Walls",
    cleanName: "Walls",
  },
  {
    id: "4",
    typeName: "PAINTBALL",
    databaseName: "Paintball",
    cleanName: "Paintball",
  },
  {
    id: "5",
    typeName: "SURVIVAL_GAMES",
    databaseName: "HungerGames",
    cleanName: "Blitz Survival Games",
  },
  {
    id: "6",
    typeName: "TNTGAMES",
    databaseName: "TNTGames",
    cleanName: "TNT Games",
  },
  {
    id: "7",
    typeName: "VAMPIREZ",
    databaseName: "VampireZ",
    cleanName: "VampireZ",
  },
  {
    id: "13",
    typeName: "WALLS3",
    databaseName: "Walls3",
    cleanName: "Mega Walls",
  },
  {
    id: "14",
    typeName: "ARCADE",
    databaseName: "Arcade",
    cleanName: "Arcade",
  },
  {
    id: "17",
    typeName: "ARENA",
    databaseName: "Arena",
    cleanName: "Arena",
  },
  {
    id: "20",
    typeName: "UHC",
    databaseName: "UHC",
    cleanName: "UHC Champions",
  },
  {
    id: "21",
    typeName: "MCGO",
    databaseName: "MCGO",
    cleanName: "Cops and Crims",
  },
  {
    id: "23",
    typeName: "BATTLEGROUND",
    databaseName: "Battleground",
    cleanName: "Warlords",
  },
  {
    id: "24",
    typeName: "SUPER_SMASH",
    databaseName: "SuperSmash",
    cleanName: "Smash Heroes",
  },
  {
    id: "25",
    typeName: "GINGERBREAD",
    databaseName: "GingerBread",
    cleanName: "Turbo Kart Racers",
  },
  {
    id: "26",
    typeName: "HOUSING",
    databaseName: "Housing",
    cleanName: "Housing",
  },
  {
    id: "51",
    typeName: "SKYWARS",
    databaseName: "SkyWars",
    cleanName: "SkyWars",
  },
  {
    id: "52",
    typeName: "TRUE_COMBAT",
    databaseName: "TrueCombat",
    cleanName: "Crazy Walls",
  },
  {
    id: "54",
    typeName: "SPEED_UHC",
    databaseName: "SpeedUHC",
    cleanName: "Speed UHC",
  },
  {
    id: "55",
    typeName: "SKYCLASH",
    databaseName: "SkyClash",
    cleanName: "SkyClash",
  },
  {
    id: "56",
    typeName: "LEGACY",
    databaseName: "Legacy",
    cleanName: "Classic Games",
  },
  {
    id: "57",
    typeName: "PROTOTYPE",
    databaseName: "Prototype",
    cleanName: "Prototype",
  },
  {
    id: "58",
    typeName: "BEDWARS",
    databaseName: "Bedwars",
    cleanName: "Bed Wars",
  },
  {
    id: "59",
    typeName: "MURDER_MYSTERY",
    databaseName: "MurderMystery",
    cleanName: "Murder Mystery",
  },
  {
    id: "60",
    typeName: "BUILD_BATTLE",
    databaseName: "BuildBattle",
    cleanName: "Build Battle",
  },
  {
    id: "61",
    typeName: "DUELS",
    databaseName: "Duels",
    cleanName: "Duels",
  },
  {
    id: "63",
    typeName: "SKYBLOCK",
    databaseName: "SkyBlock",
    cleanName: "SkyBlock",
  },
];
